#!/bin/bash

NAME="qb-container"

if [ "$(docker ps -q -f name=$NAME)" ]; then 
    docker stop $NAME
	docker remove $NAME 
	echo "$NAME is stopped"
else 
	echo "$NAME is not running"
fi

docker run -d -p 5432:5432 --name qb-container -e POSTGRES_PASSWORD=password postgres

npx prisma db push
